export let state = {
  balance: 0,
  incomePerSec: 0,
  prestigeCount: 0,
  prestigePoints: 0,
  prestigeBonus: 1,
  employees: {
    junior: 0,
    senior: 0,
    lead: 0,
    ai: 0,
    remote: 0,
  },
  upgrades: {
    click: false,
    passive: false,
  },
  clickMultiplier: 1,
  passiveMultiplier: 1,
  unlockedPerks: [],
  eventActive: false,
  eventModifier: 1,
  matrixEnabled: true,
  theme: "dark",
  selectedProject: null,
  activeProjects: {},
  projectsData: [
    {
      id: "site",
      name: "Site Vitrine",
      cost: 500,
      duration: 10,
      employees: { junior: 1 },
      reward: 1000,
    },
    {
      id: "app",
      name: "App Mobile",
      cost: 5000,
      duration: 30,
      employees: { senior: 2 },
      reward: 12000,
    },
    {
      id: "saas",
      name: "SaaS Complet",
      cost: 20000,
      duration: 60,
      employees: { lead: 1 },
      reward: 60000,
    },
    {
      id: "ai",
      name: "IA sur mesure",
      cost: 50000,
      duration: 120,
      employees: { ai: 1 },
      reward: 150000,
    },
  ],
  employeeSalaries: {
    junior: 0.05,
    senior: 0.5,
    lead: 2,
    ai: 10,
    remote: 20,
  },
  availablePerks: [
    {
      id: "clickBoost",
      name: "Boost Clic",
      cost: 1,
      desc: "+10% €/clic permanent",
    },
    {
      id: "passiveBoost",
      name: "Boost Passif",
      cost: 1,
      desc: "+10% €/sec permanent",
    },
    {
      id: "eventLuck",
      name: "Événements Positifs",
      cost: 2,
      desc: "+10% chance Hackathon",
    },
    {
      id: "salaryReduction",
      name: "Réduction Salaires",
      cost: 3,
      desc: "-10% sur salaires",
    },
    {
      id: "bugImmunity",
      name: "Production Stable",
      cost: 2,
      desc: "Immunité aux bugs critiques",
    },
  ],
  tipsUnlocked: [],
  allTips: [
    {
      id: "salary",
      text: "💸 Les salaires sont payés chaque seconde. Planifie tes coûts !",
    },
    {
      id: "risk",
      text: "⚠️ Les projets Risky peuvent te ruiner ou te rendre riche.",
    },
    {
      id: "perks",
      text: "✨ Utilise tes points de prestige pour acheter des perks stratégiques.",
    },
    {
      id: "bugs",
      text: "🐞 Les événements critiques réduisent ta production.",
    },
    {
      id: "matrix",
      text: "🌌 Le fond Matrix est purement esthétique. Mais il en impose.",
    },
    {
      id: "remote",
      text: "🌍 Les équipes Remote coûtent cher mais rapportent beaucoup.",
    },
  ],
};
